# Generated by Django 2.2.24 on 2021-12-20 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_needed', models.IntegerField()),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_has_next', models.BooleanField(default=False)),
                ('right_has_next', models.BooleanField(default=False)),
                ('current_game', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='tournaments.Game')),
                ('left_round', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='l_round', to='tournaments.Round')),
                ('right_round', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='r_round', to='tournaments.Round')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=200)),
                ('tournament_format', models.CharField(max_length=200)),
                ('start', models.DateField(default='1970-01-01')),
                ('end', models.DateField(default='1970-01-01')),
                ('is_open', models.BooleanField(default=False)),
                ('subscribe_date', models.DateField(default='1970-01-01')),
                ('final_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round')),
            ],
        ),
    ]
