# Generated by Django 2.2.24 on 2021-12-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20211220_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='subscribe_date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
