# Generated by Django 2.2.24 on 2021-12-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20211220_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_format_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
