# Generated by Django 2.2.24 on 2021-12-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_in_tournament', to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='in_tournament', to='tournaments.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='final_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_round', to='tournaments.Round'),
        ),
    ]
