# Generated by Django 2.2.24 on 2021-12-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20211223_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_format',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
