# Generated by Django 2.2.24 on 2021-11-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='date_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
