# Generated by Django 2.2.24 on 2021-12-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='format',
            field=models.CharField(default='1|0', max_length=10),
            preserve_default=False,
        ),
    ]
