# Generated by Django 2.2.24 on 2021-12-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_chessgame_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
