# Generated by Django 2.2.24 on 2021-12-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_chessgame_won'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chessgame',
            old_name='won',
            new_name='over',
        ),
    ]
